In [1]:
import pandas as pd
df = pd.read_csv('atlanta temp.csv')
df.head()

year    jan    fev    mar   apr   may   jun   jul   aug   sep   oct   nov  \
0  1879   4.29   3.09   2.49  3.98  4.16  3.20  5.75  4.76  1.43  5.44  3.88   
1  1880   2.86   3.11  11.87  7.07  4.52  3.57  3.16  3.61  6.21  2.81  8.21   
2  1881   8.35  10.41  10.98  4.58  1.27  2.46  0.56  4.10  3.76  3.44  4.30   
3  1882   6.40  10.29   4.16  5.21  3.02  3.22  6.61  5.56  3.71  1.35  4.22   
4  1883  15.82   3.22   3.73  8.20  2.00  2.31  1.06  2.73  1.38  1.52  4.72   

    dec  annual  
0  7.86   50.33  
1  5.70   62.70  
2  7.53   61.74  
3  4.37   58.12  
4  4.84   51.53

In [2]:
len(df)

140

In [4]:
values_df = df.values

In [5]:
values_df[0]

array([1879, 4.29, 3.09, 2.49, 3.98, 4.16, 3.2, 5.75, 4.76, 1.43, '5.44',
       3.88, 7.86, 50.33], dtype=object)

In [6]:
len(values_df)

140

In [11]:
len(values_df[0])

14

In [12]:
values_df.shape

(140, 14)

In [13]:
values_df[0][1:-1]

array([4.29, 3.09, 2.49, 3.98, 4.16, 3.2, 5.75, 4.76, 1.43, '5.44', 3.88,
       7.86], dtype=object)

In [16]:
temp_series = values_df[:,1:-1]

In [17]:
temp_series.shape

(140, 12)

In [18]:
temp_series[0]

array([4.29, 3.09, 2.49, 3.98, 4.16, 3.2, 5.75, 4.76, 1.43, '5.44', 3.88,
       7.86], dtype=object)

In [24]:
import numpy as np
np.reshape(temp_series,1680, order = False)
temp_series.shape
140*12

1680

In [22]:
temp_series[:16]

array([[4.29, 3.09, 2.49, 3.98, 4.16, 3.2, 5.75, 4.76, 1.43, '5.44',
        3.88, 7.86],
       [2.86, 3.11, 11.87, 7.07, 4.52, 3.57, 3.16, 3.61, 6.21, '2.81',
        8.21, 5.7],
       [8.35, 10.41, 10.98, 4.58, 1.27, 2.46, 0.56, 4.1, 3.76, '3.44',
        4.3, 7.53],
       [6.4, 10.29, 4.16, 5.21, 3.02, 3.22, 6.61, 5.56, 3.71, '1.35',
        4.22, 4.37],
       [15.82, 3.22, 3.73, 8.2, 2.0, 2.31, 1.06, 2.73, 1.38, '1.52',
        4.72, 4.84],
       [5.2, 5.84, 9.7, 5.86, 1.37, 10.73, 2.42, 2.06, 0.08, '0.70',
        2.84, 6.09],
       [8.44, 4.14, 4.26, 1.31, 6.08, 4.83, 4.02, 6.92, 6.51, '3.94',
        3.98, 2.64],
       [7.33, 1.53, 11.16, 2.52, 6.21, 8.68, 2.08, 2.36, 0.53, '0.03',
        5.32, 3.03],
       [3.52, 3.74, 1.99, 1.38, 1.76, 2.82, 14.11, 7.51, 4.2, '3.28',
        0.3, 5.79],
       [3.89, 5.91, 8.16, 1.34, 6.86, 4.71, 1.85, 3.89, 14.26, '3.99',
        4.7, 5.42],
       [6.39, 5.28, 2.49, 2.54, 3.16, 5.03, 8.83, 6.73, 6.32, '2.21',
        5.17, 0.6],
   